import { AddUser } from './add-user';

export const USERS: AddUser[] = [
   {
      userID: 1,
      firstName: 'Mor',
      lastName: 'Kairé',
      email: 'km@test.com',
      phone: 778292973,
      direction: 'DSI',
      department: 'INS',
      service: 'IRCP',
      poste: 'Ingénieur informatique',
   },
   {
      userID: 2,
      firstName: 'Amy',
      lastName: 'Sidibé',
      email: 'amy@test.com',
      phone: 775663573,
      direction: 'DSI',
      department: 'INS',
      service: 'IRCP',
      poste: 'Ingénieur informatique',
   },
   {
      userID: 3,
      firstName: 'Maty',
      lastName: 'Diaw',
      email: 'md@test.com',
      phone: 777248175,
      direction: 'DSI',
      department: 'ILAB',
      service: '',
      poste: 'Ingénieur informatique',
   },
   {
      userID: 4,
      firstName: 'Oulymata',
      lastName: 'Seck',
      email: 'Os@test.com',
      phone: 769163862,
      direction: 'DSI',
      department: 'DIF',
      service: 'SSI',
      poste: 'Ingénieur informatique',
   },
   {
      userID: 5,
      firstName: 'Samba',
      lastName: 'Sougou',
      email: 'amy@test.com',
      phone: 782543671,
      direction: 'DSI',
      department: 'DIF',
      service: 'DSS',
      poste: 'Ingénieur informatique',
   },
   {
      userID: 6,
      firstName: 'Tidiane',
      lastName: 'Mangassouba',
      email: 'tmsquare@test.com',
      phone: 782534719,
      direction: 'DSI',
      department: 'ILAB',
      service: '',
      poste: 'Ingénieur informatique',
   },
   {
      userID: 7,
      firstName: 'Mouhamadou',
      lastName: 'Gaye',
      email: 'mg@test.com',
      phone: 764235165,
      direction: 'DSI',
      department: 'DAC',
      service: 'SOC',
      poste: 'Ingénieur informatique',
   }
];
